#!/usr/bin/env python3
"""Generate project compatibility fixtures by executing the historical app itself.

Requires:
  - full git history (checkout fetch-depth: 0)
  - playwright + Chromium

The output is intentionally generated from the historical JavaScript rather than
hand-authored. This prevents tests from freezing assumptions that were never
actually serialized by ValiStruct.
"""
from __future__ import annotations
from pathlib import Path
from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler
import argparse
import contextlib
import io
import json
import os
import socket
import subprocess
import tarfile
import tempfile
import threading

from playwright.sync_api import sync_playwright

ROOT=Path(__file__).resolve().parents[1]
DEFAULT_REVISIONS={
    "project_v3_0_rc6.json":"75893d243146b48a1e4c8b38e715b428373f861e",
    "project_v5_2_4.json":"38084251d1456b39a173d6520ef6e30c8554b40a",
}

def extract_revision(revision: str, destination: Path) -> None:
    archive=subprocess.run(
        ["git","archive","--format=tar",revision],
        cwd=ROOT,check=True,capture_output=True
    ).stdout
    with tarfile.open(fileobj=io.BytesIO(archive),mode="r:") as tf:
        tf.extractall(destination)

class QuietHandler(SimpleHTTPRequestHandler):
    def log_message(self,*_args):
        pass

@contextlib.contextmanager
def serve(folder: Path):
    old=os.getcwd()
    os.chdir(folder)
    try:
        server=ThreadingHTTPServer(("127.0.0.1",0),QuietHandler)
        thread=threading.Thread(target=server.serve_forever,daemon=True)
        thread.start()
        yield f"http://127.0.0.1:{server.server_port}"
    finally:
        server.shutdown()
        server.server_close()
        os.chdir(old)

def capture_state(url: str) -> dict:
    with sync_playwright() as p:
        browser=p.chromium.launch(headless=True)
        page=browser.new_page()
        page.on("dialog",lambda dialog: dialog.dismiss())
        page.goto(url+"/index.html",wait_until="load")
        page.wait_for_function("typeof projectState === 'function'",timeout=15000)
        state=page.evaluate("""() => {
          const name=document.getElementById('projectName');
          const author=document.getElementById('projectAuthor');
          if(name)name.value='Fixture histórico';
          if(author)author.value='Dr. Roberto Joel Tirado Reyes';
          try { localStorage.removeItem('valistruct_privacy_v21'); } catch (_) {}
          return projectState();
        }""")
        browser.close()
        return state

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--out",default="tests/fixtures/projects")
    args=parser.parse_args()
    out=(ROOT/args.out).resolve()
    out.mkdir(parents=True,exist_ok=True)
    for filename,revision in DEFAULT_REVISIONS.items():
        with tempfile.TemporaryDirectory() as tmp:
            folder=Path(tmp)
            extract_revision(revision,folder)
            with serve(folder) as url:
                state=capture_state(url)
        payload={
            "_fixture": {
                "generatedFromRevision": revision,
                "generator":"tools/generate_project_fixtures.py",
                "note":"Generated by executing historical projectState(); do not hand-edit."
            },
            "project":state,
        }
        (out/filename).write_text(
            json.dumps(payload,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"
        )
        print(f"wrote {out/filename}")

if __name__=="__main__":
    main()
